# Generated by Django 4.2.29 on 2026-04-05 08:48

from django.db import migrations, models
import transfer_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('File', '0003_uploadedfile_original_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='expires_at',
            field=models.DateTimeField(default=transfer_app.models.default_expiry),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
